// frontend/react-baseline/src/components/Product.js
import React from 'react'

let im = require('../assets/box.svg')

function Product(props) {
	return (
		<div className="product">
            <img className="product-image" src={im} alt={"image of product: " + props.name} ></img>
			<h2>{props.name}</h2>
			<p>{props.description}</p>
			<p>€ {props.price.toFixed(2)}</p>
		</div>
	)
}

export default Product

// frontend/lit-elements/elements/product.js
import { LitElement, html } from 'lit-element'
import im from '../assets/box.svg'

class Product extends LitElement {
	static get properties() {
		return {
			alt: { type: String },
		}
	}

	constructor() {
		super()
		this.alt = 'No alt text given for product image'
	}

	render() {
		console.log('render product')
		return html`
			<style>
				.mf-poc-product {
					text-align: center;
					padding: 10px;
				}
				.mf-poc-product-image {
					width: 45%;
					margin-top: 2rem;
				}
			</style>
			<div class="mf-poc-product">
				<img class="mf-poc-product-image" src=${im} alt='${this.alt}'></img>
                <h1><slot name="name">Default Name</slot></h1>
                <p><slot name="description">Default Description</slot></p>
                <p>€ <slot name="price">Default Price</slot></p>
            </div> 
        `
	}
}

customElements.define('product-element', Product)
