// frontend/angular-lit-elements/src/app/app.component.ts
import { Component, HostListener } from '@angular/core';
import 'micro-frontend-poc-delaware-ugent'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})

export class AppComponent {

  message = null

  @HostListener('document:products:trigger', ['$event'])
  setMessage(event){
    this.message = `Received a message from the micro frontend: ${event.detail.amount} products are displayed`
    setTimeout(()=>{
      this.message = null
    }, 3000)
  }
  
  sendEvent(){
    document.dispatchEvent(new CustomEvent('container:trigger'));
  }
}


<div class="app-container">
  <div>
    <hr />
    <div class="page-titles">
      <h1 class="big-title">Micro Frontend<br />POC  <span class="red version">Angular + LitElement</span></h1>
      <h1 class="medium-title">delaware <span class="red">-</span> UGent</h1>
    </div>
    <p class="landing-text">
      This app was created with <a href="https://angular.io/">Angular</a>. It acts as the frontend container application that uses the micro frontend that was created as a POC.</p>
      <p>Click <button (click)="sendEvent()">here</button> to communicate with the micro frontend. </p>
      <p className="landing-text">{{message}}</p>
      <product-list url='http://gateway:2003/products/normal' expanding></product-list>
      <img class="bg-image" src="./assets/bg.png" alt="background hexagonal shapes">
  </div>
</div>

// frontend/react-baseline/src/App.js
import React from 'react'
import './App.css'

import ProductList from './components/ProductList'

const background = require('./assets/bg.png')

function App() {
	return (
		<div className="app-container">
			<div>
				<hr />
				<div className="page-titles">
					<h1 className="big-title">Micro Frontend<br />POC <span className="red version">React</span></h1>
					<h1 className="medium-title">delaware <span className="red">-</span> UGent</h1>
				</div>
			</div>
			<p className="landing-text">
				This app was created with <a href="https://reactjs.org/">React</a>. It acts as the frontend monolith that will be the baseline for the POC.
			</p>
			<ProductList></ProductList>
			<img className="bg-image" src={background} alt="background hexagonal shapes"></img>
		</div>
	)
}

export default App
