// frontend/react-custom-elements/src/App.js
import React, { useEffect, useState } from 'react'
import './App.css'

import 'micro-frontend-pre-poc-delaware-ugent'

const background = require('./assets/bg.png')
const url = 'http://gateway:2003/products/normal'

function App() {
	const [message, setMessage] = useState(null)
	const [products, setProducts] = useState([])

	useEffect(() => {
		
		fetch(url)
			.then((res) => res.json())
			.then((body) => {
				setProducts(body)
			})

		document.addEventListener('products:trigger', (event) => {
			setMessage(
				`Received a message from the micro frontend: ${event.detail.amount} products are displayed`
			)
			setTimeout(() => {
				setMessage(null)
			}, 10000)
		})
		return () => {
			document.removeEventListener('products:trigger')
		}
	}, [])

	return (
		<div className="app-container">
			<div>
				<hr />
				<div className="page-titles">
					<h1 className="big-title">
						Micro Frontend
						<br />
						POC <span className="red version">React + Web Components</span>
					</h1>
					<h1 className="medium-title">
						delaware <span className="red">-</span> UGent
					</h1>
				</div>
			</div>
			<p className="landing-text">
				This app was created with <a href="https://reactjs.org/">React</a>. It acts as the
				frontend monolith that will be the baseline for the POC.
			</p>
			<p>
				Click{' '}
				<button
					onClick={() => {
						document.dispatchEvent(new CustomEvent('container:trigger'))
					}}
				> 
					here
				</button>{' '}
				to communicate with the micro frontend.
			</p>
			<p className="landing-text">
				Click <button onClick={()=>{
					let updated = [...products]
					updated[0].name = "Random " + Math.round(Math.random()*100)
					setProducts(updated)
				}}>here</button> to change the productlist that is shown.
			</p>
			{message && <p className="landing-text">{message}</p>}
			<product-list expanding products={JSON.stringify(products)}></product-list> 
			<img className="bg-image" src={background} alt="background hexagonal shapes"></img>
		</div> 
	)
}

export default App

// frontend/angular-lit-elements/src/app/app.component.ts
import { Component, HostListener, OnInit } from '@angular/core';
import fetch from 'node-fetch'
import 'micro-frontend-poc-delaware-ugent'

const url = 'http://gateway:2003/products/normal'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})

export class AppComponent implements OnInit {

  message = null

  products = []

  pAttr = ""

  ngOnInit(){
    fetch(url)
			.then((res) => res.json())
			.then((body) => {
        this.products = body
        this.pAttr = JSON.stringify(this.products)
			})
  }
  
  @HostListener('document:products:trigger', ['$event'])
  setMessage(event){
    this.message = `Received a message from the micro frontend: ${event.detail.amount} products are displayed`
    setTimeout(()=>{
      this.message = null
    }, 3000)
  }
  
  sendEvent(){
    document.dispatchEvent(new CustomEvent('container:trigger'));
  }

  handleClick(){
    this.products[0].name = "Random " + Math.round(Math.random()*100)
    this.pAttr = JSON.stringify(this.products)
  }
}


<div class="app-container">
  <div>
    <hr />
    <div class="page-titles">
      <h1 class="big-title">Micro Frontend<br />POC  <span class="red version">Angular + LitElement</span></h1>
      <h1 class="medium-title">delaware <span class="red">-</span> UGent</h1>
    </div>
    <p class="landing-text">
      This app was created with <a href="https://angular.io/">Angular</a>. It acts as the frontend container application that uses the micro frontend that was created as a POC.</p>
      <p>Click <button (click)="sendEvent()">here</button> to communicate with the micro frontend. </p>
      <p>
				Click <button (click)="handleClick()">here</button> to change the productlist that gets passed down.
      </p>
      <p className="landing-text">{{message}}</p>
      <product-list products='{{pAttr}}' expanding>
      </product-list>
      <img class="bg-image" src="./assets/bg.png" alt="background hexagonal shapes">
  </div>
</div>
